<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

# I. Cài đặt

## Cài đặt thư viện

In [3]:
!pip install -U vnstock3

Requirement already satisfied: vnstock3 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (0.3.0.6)
Requirement already satisfied: requests in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (2.32.3)
Requirement already satisfied: beautifulsoup4 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (4.12.3)
Requirement already satisfied: pandas in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (2.2.2)
Requirement already satisfied: vnai>=0.1.3 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (0.1.3)
Requirement already satisfied: openpyxl in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (3.1.5)
Requirement already satisfied: pydantic in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (2.8.2)
Requirement already satisfied: psutil in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (6.0.0)
Requirement already satisfied: fake-useragent in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (1.5.1)
Requirement already satisfied: vnstock-ezchart in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock3) (0.0.2)
Requirement already satisfied: cryptography in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnai>=0.1.3->vnstock3) (43.0.0)
Requirement already satisfied: soupsieve>1.2 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from beautifulsoup4->vnstock3) (2.5)
Requirement already satisfied: et-xmlfile in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from openpyxl->vnstock3) (1.1.0)
Requirement already satisfied: numpy>=1.22.4 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pandas->vnstock3) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pandas->vnstock3) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pandas->vnstock3) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pandas->vnstock3) (2024.1)
Requirement already satisfied: annotated-types>=0.4.0 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pydantic->vnstock3) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pydantic->vnstock3) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from pydantic->vnstock3) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from requests->vnstock3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from requests->vnstock3) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from requests->vnstock3) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from requests->vnstock3) (2024.7.4)
Requirement already satisfied: squarify in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock-ezchart->vnstock3) (0.4.4)
Requirement already satisfied: wordcloud in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock-ezchart->vnstock3) (1.9.3)
Requirement already satisfied: vnstock in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from vnstock-ezchart->vnstock3) (0.2.9.2.2)
Requirement already satisfied: six>=1.5 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock3) (1.16.0)
Requirement already satisfied: cffi>=1.12 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from cryptography->vnai>=0.1.3->vnstock3) (1.17.0)
Requirement already satisfied: pillow in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from wordcloud->vnstock-ezchart->vnstock3) (10.4.0)
Requirement already satisfied: matplotlib in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from wordcloud->vnstock-ezchart->vnstock3) (3.9.1.post1)
Requirement already satisfied: pycparser in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from cffi>=1.12->cryptography->vnai>=0.1.3->vnstock3) (2.22)
Requirement already satisfied: contourpy>=1.0.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (1.2.1)
Requirement already satisfied: cycler>=0.10 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (1.4.5)
Requirement already satisfied: packaging>=20.0 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in e:\user\miniconda3\envs\ai_prj_final\lib\site-packages (from matplotlib->wordcloud->vnstock-ezchart->vnstock3) (3.1.2)

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [4]:
## Nạp toàn bộ thư viện
# from vnstock3 import *

## Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock3 import Vnstock

# II. Truy xuất dữ liệu - CK Việt Nam

* Khởi tạo đối tượng stock để dùng cho tất cả thao tác truy xuất dữ liệu chứng khoán về sau. Luồng công việc minh hoạ dưới đây giả định bạn bắt đầu với 1 mã chứng khoán cần phân tích, mặc định là VN30F1M. Bạn có thể thay đổi sang mã bất kỳ bằng cách nhập tham số `symbol` tại hàm chức năng thay vì khởi tạo lại đối tượng. Ví dụ, mã `VN30F1M` được gán khi tạo đối tượng, nhưng khi gọi dữ liệu giá lịch sử, bạn có thể cập nhật mã mới là `ACB` thay vì khởi tạo lại đối tượng một cách bất tiện: `stock.quote.history(symbol='ACB', start='2020-01-01', end='2024-12-31')`

* Chọn nguồn dữ liệu thuộc danh sách được hỗ trợ: VCI, TCBS cho chứng khoán trong nước, MSN cho dữ liệu chứng khoán quốc tế và sàn HOSE.

In [5]:
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='ACB', source='VCI')

2024-08-12 16:55:39,369 - vnstock3.common.data.data_explorer - WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS

## Listing: Liệt kê danh sách chứng khoán

### Danh sách tất cả mã CK niêm yết (đơn giản)

In [6]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
stock.listing.all_symbols()

     ticker                                         organ_name
0       A32                                 Công ty Cổ phần 32
1       AAA                  Công ty Cổ phần Nhựa An Phát Xanh
2       AAM                    Công ty Cổ Phần Thủy Sản MeKong
3       AAS            Công ty Cổ phần Chứng khoán SmartInvest
4       AAT        Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa
...     ...                                                ...
1593    XPH                    Công ty Cổ phần Xà phòng Hà Nội
1594    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
1595    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
1596    YEG                     Công ty Cổ phần Tập đoàn Yeah1
1597    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...

[1598 rows x 2 columns]

### Liệt kê mã CP theo sàn (đầy đủ)

In [7]:
# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
stock.listing.symbols_by_exchange()

,symbol,id,type,exchange,en_organ_name,en_organ_short_name,organ_short_name,organ_name
0,YTC,8425620,STOCK,UPCOM,Ho Chi Minh City Medical Import Export Joint S...,YTECO,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,8424579,STOCK,HSX,Yeah1 Group Corporation,Yeah1 Group,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,8424470,STOCK,HSX,Yen Bai Industry Mineral Joint Stock Company,Yen Bai Industry Mineral,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,8425710,STOCK,UPCOM,YenBai Cement and Minerals Joint Stock Company,YenBai Cement and Minerals,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,8425864,STOCK,UPCOM,Hanoi Soap Joint Stock Company,Hanoi Soap,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...,...,...,...
2542,AAS,8425599,STOCK,UPCOM,Smart Invest Securities Joint Stock Company,SmartInvest Securities,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2543,AAM,8424957,STOCK,HSX,Mekong Fisheries Joint Stock Company,Mekong Fisheries,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2544,AAH,13216673,STOCK,UPCOM,Hop Nhat Joint Stock Company,Hop Nhat Coal,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2545,AAA,8424464,STOCK,HSX,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2546,A32,8425330,STOCK,UPCOM,32 Joint Stock Company,32 Company,Công ty 32,Công ty Cổ phần 32

### Liệt kê mã CP theo ngành icb

In [8]:
stock.listing.symbols_by_industries()

,symbol,organ_name,en_organ_name,icb_name3,en_icb_name3,icb_name2,en_icb_name2,icb_name4,en_icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,CCC,Công ty Cổ Phần Xây Dựng CDC,CDC Construction Joint Stock Company,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Xây dựng,Heavy Construction,CT,2000,2300,2350,2357
1,HIO,Công ty Cổ Phần Helio Energy,Helio Energy Joint Stock Company,Sản xuất & Phân phối Điện,Electricity,"Điện, nước & xăng dầu khí đốt",Utilities,Sản xuất & Phân phối Điện,Conventional Electricity,CT,7000,7500,7530,7535
2,TSA,Công ty Cổ Phần Đầu Tư Và Xây Lắp Trường Sơn,Truong Son Investment And Construction Joint S...,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Xây dựng,Heavy Construction,CT,2000,2300,2350,2357
3,CST,Công ty Cổ phần Than Cao Sơn - TKV,Cao Son Coal Joint Stock Company,Khai khoáng,Mining,Tài nguyên Cơ bản,Basic Resources,Khai thác Than,Coal,CT,1000,1700,1770,1771
4,SGI,Công ty Cổ phần Đầu tư phát triển Sài Gòn 3 Group,Sai Gon 3 Group Investment Development Joint S...,Hàng cá nhân,Personal Goods,Hàng cá nhân & Gia dụng,Personal & Household Goods,Hàng May mặc,Clothing & Accessories,CT,3000,3700,3760,3763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1584,VXB,Công ty Cổ phần Vật liệu xây dựng Bến Tre,Ben Tre Construction Material Joint Stock Company,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Vật liệu xây dựng & Nội thất,Building Materials & Fixtures,CT,2000,2300,2350,2353
1585,X26,Công ty Cổ phần 26,26 Joint Stock Company,Hàng cá nhân,Personal Goods,Hàng cá nhân & Gia dụng,Personal & Household Goods,Hàng May mặc,Clothing & Accessories,CT,3000,3700,3760,3763
1586,WCS,Công ty Cổ phần Bến xe Miền Tây,West Coach Station Joint Stock Company,Vận tải,Industrial Transportation,Hàng & Dịch vụ Công nghiệp,Industrial Goods & Services,"Kho bãi, hậu cần và bảo dưỡng",Transportation Services,CT,2000,2700,2770,2777
1587,X77,Công ty Cổ phần Thành An 77,Thanh An 77 Joint Stock Company,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Vật liệu xây dựng & Nội thất,Building Materials & Fixtures,CT,2000,2300,2350,2353
1588,BCO,Công ty Cổ phần Xây dựng Bình Phước,Binh Phuoc Construction Joint Stock Company,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Xây dựng,Heavy Construction,CT,2000,2300,2350,2357

### Danh sách cổ phiếu theo nhóm

In [9]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
stock.listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     BVH
4     CTG
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    MBB
11    MSN
12    MWG
13    PLX
14    POW
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

### Danh sách mã ngành theo mã icb

In [10]:
stock.listing.industries_icb()

,icb_name,en_icb_name,icb_code,level
0,Sản xuất Dầu khí,Oil & Gas Producers,0530,3
1,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",0570,3
2,Hóa chất,Chemicals,1350,3
3,Lâm nghiệp và Giấy,Forestry & Paper,1730,3
4,Kim loại,Industrial Metals & Mining,1750,3
...,...,...,...,...
151,Viễn thông,Telecommunications,6000,1
152,Tiện ích Cộng đồng,Utilities,7000,1
153,Tài chính,Financials,8000,1
154,Ngân hàng,Banks,8301,1
155,Công nghệ Thông tin,Technology,9000,1

## Quote: Giá chứng khoán

#### Giá lịch sử

In [11]:
df = stock.quote.history(start='2024-01-01', end='2024-08-11', interval='1D')
df

                   time   open   high    low  close    volume
0   2024-01-02 07:00:00  20.12  20.79  20.12  20.54  13896933
1   2024-01-03 07:00:00  20.58  21.00  20.37  21.00   9817807
2   2024-01-04 07:00:00  21.17  21.55  21.08  21.25  23605373
3   2024-01-05 07:00:00  21.25  21.38  21.04  21.38   9282598
4   2024-01-08 07:00:00  21.59  21.63  21.17  21.29  12398885
..                  ...    ...    ...    ...    ...       ...
145 2024-08-05 07:00:00  23.60  23.85  23.15  23.20  20086500
146 2024-08-06 07:00:00  23.50  23.65  23.25  23.50   8020900
147 2024-08-07 07:00:00  23.60  23.60  23.30  23.40   4400300
148 2024-08-08 07:00:00  23.25  23.50  23.25  23.25   3649600
149 2024-08-09 07:00:00  23.40  23.60  23.30  23.60   3006900

[150 rows x 6 columns]

In [12]:
# Tất cả dataframe dữ liệu sẽ được gán thuộc tính tên và loại tài sản tương ứng
print(f'Mã chứng khoán: {df.name}')
print(f'Loại tài sản: {df.category}')

Mã chứng khoán: ACB
Loại tài sản: stock

#### Intraday: dữ liệu khớp lệnh

In [13]:
# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
stock.quote.intraday(symbol='ACB', show_log=False)

                  time    price  volume match_type         id
99 2024-08-12 14:26:39  23700.0   10600        Buy  231059274
98 2024-08-12 14:26:45  23700.0     200        Buy  231059540
97 2024-08-12 14:26:49  23700.0     100        Buy  231059663
96 2024-08-12 14:26:53  23700.0     300        Buy  231059846
95 2024-08-12 14:26:59  23700.0     500        Buy  231060110
..                 ...      ...     ...        ...        ...
4  2024-08-12 14:29:20  23700.0    1000        Buy  231066031
3  2024-08-12 14:29:26  23700.0    2000        Buy  231066286
2  2024-08-12 14:29:32  23700.0    1000        Buy  231066438
1  2024-08-12 14:29:33  23650.0     100       Sell  231066504
0  2024-08-12 14:44:35  23800.0  482800    ATO/ATC  231067170

[100 rows x 5 columns]

In [14]:
# Bước giá và khối lượng giao dịch: realtime
stock.quote.price_depth('ACB')

    price acc_volume acc_buy_volume acc_sell_volume acc_undefined_volume
0   23800     482800              0               0               482800
1   23750     137300         137300               0                    0
2   23700     447400         371100           76300                    0
3   23650      81300          70500           10800                    0
4   23600     238200         208100               0                30100
5   23550     113800         109400            4400                    0
6   23500     386200         291500           94700                    0
7   23450     555400         292300          263100                    0
8   23400    1077600         320800          756800                    0
9   23350     654400              0          654400                    0
10  23300      22900              0           22900                    0

## Trading: Giao dịch

### Bảng giá

In [15]:
stock.trading.price_board(['ACB'])

  listing                                                                 \
   symbol ceiling  floor ref_price stock_type exchange last_trading_date
0     ACB   25250  21950     23600      STOCK      HSX

                                ...     bid_ask                           \
  listed_share   type       id  ... bid_2_price bid_2_volume bid_3_price
0   4466657912  STOCK  8424512  ...       23650        27400       23600

                                                                              \
  bid_3_volume ask_1_price ask_1_volume ask_2_price ask_2_volume ask_3_price
0        48600       23800       171500       23850       117400       23900


  ask_3_volume
0       157600

[1 rows x 39 columns]

In [16]:
stock.trading.price_board(['VCB','ACB','TCB','BID']).T # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

                                                                                  0  \
listing symbol                                                                  VCB
        ceiling                                                               93800
        floor                                                                 81600
        ref_price                                                             87700
        stock_type                                                            STOCK
        exchange                                                                HSX
        last_trading_date
        listed_share                                                     5589091262
        type                                                                  STOCK
        id                                                                  8424561
        organ_name                Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
        prior_close_price                                                     87700
        benefit
match   match_price                                                           87800
        match_vol                                                            176900
        accumulated_volume                                                  1060300
        accumulated_value                                                     93052
        avg_match_price                                                87760.067905
        highest                                                               88400
        lowest                                                                87300
        match_type                                                          unknown
        foreign_sell_volume                                                  432914
        foreign_buy_volume                                                   258900
        current_room                                                      375093476
        total_room                                                       1676727378
        total_accumulated_value                                            93052.13
        total_accumulated_volume                                              10603
bid_ask bid_1_price                                                           87800
        bid_1_volume                                                          17500
        bid_2_price                                                           87700
        bid_2_volume                                                           2500
        bid_3_price                                                           87600
        bid_3_volume                                                          16000
        ask_1_price                                                           88000
        ask_1_volume                                                           1400
        ask_2_price                                                           88100
        ask_2_volume                                                           6100
        ask_3_price                                                           88200
        ask_3_volume                                                          20600

                                                                    1  \
listing symbol                                                    ACB
        ceiling                                                 25250
        floor                                                   21950
        ref_price                                               23600
        stock_type                                              STOCK
        exchange                                                  HSX
        last_trading_date
        listed_share                                       4466657912
        type                                                    STOCK
        id                                                    8424512
        organ_name                Ngân hàng Thương mại Cổ phần Á Châu
        prior_close_price                                       23600
        benefit
match   match_price                                             23800
        match_vol                                              482800
        accumulated_volume                                    4197300
        accumulated_value                                       98708
        avg_match_price                                  23517.022848
        highest                                                 23800
        lowest                                                  23300
        match_type                                            unknown
        foreign_sell_volume                                    761300
        foreign_buy_volume                                     761300
        current_room                                                0
        total_room                                         1339997373
        total_accumulated_value                              98708.63
        total_accumulated_volume                                41973
bid_ask bid_1_price                                             23700
        bid_1_volume                                             5000
        bid_2_price                                             23650
        bid_2_volume                                            27400
        bid_3_price                                             23600
        bid_3_volume                                            48600
        ask_1_price                                             23800
        ask_1_volume                                           171500
        ask_2_price                                             23850
        ask_2_volume                                           117400
        ask_3_price                                             23900
        ask_3_volume                                           157600

                                                                                2  \
listing symbol                                                                TCB
        ceiling                                                             22550
        floor                                                               19650
        ref_price                                                           21100
        stock_type                                                          STOCK
        exchange                                                              HSX
        last_trading_date
        listed_share                                                   7045021622
        type                                                                STOCK
        id                                                                8424683
        organ_name                Ngân hàng Thương mại Cổ phần Kỹ thương Việt Nam
        prior_close_price                                                   21100
        benefit
match   match_price                                                         21250
        match_vol                                                          859400
        accumulated_volume                                               10346600
        accumulated_value                                                  218495
        avg_match_price                                               21117.56519
        highest                                                             21250
        lowest                                                              21000
        match_type                                                        unknown
        foreign_sell_volume                                               2907000
        foreign_buy_volume                                                 799200
        current_room                                                     78560973
        total_room                                                     1584143561
        total_accumulated_value                                         218495.63
        total_accumulated_volume                                           103466
bid_ask bid_1_price                                                         21200
        bid_1_volume                                                        35500
        bid_2_price                                                         21150
        bid_2_volume                                                       212800
        bid_3_price                                                         21100
        bid_3_volume                                                       143700
        ask_1_price                                                         21250
        ask_1_volume                                                       146300
        ask_2_price                                                         21300
        ask_2_volume                                                       449800
        ask_3_price                                                         21350
        ask_3_volume                                                       933300

                                                                                  3
listing symbol                                                                  BID
        ceiling                                                               49950
        floor                                                                 43450
        ref_price                                                             46700
        stock_type                                                            STOCK
        exchange                                                                HSX
        last_trading_date
        listed_share                                                     5700435900
        type                                                                  STOCK
        id                                                                  8424583
        organ_name                Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...
        prior_close_price                                                     46700
        benefit
match   match_price                                                           46800
        match_vol                                                            203600
        accumulated_volume                                                  1358400
        accumulated_value                                                     63826
        avg_match_price                                                46986.160188
        highest                                                               47350
        lowest                                                                46500
        match_type                                                          unknown
        foreign_sell_volume                                                  278539
        foreign_buy_volume                                                   292500
        current_room                                                      727561636
        total_room                                                       1710130770
        total_accumulated_value                                           63826.695
        total_accumulated_volume                                              13584
bid_ask bid_1_price                                                           46800
        bid_1_volume                                                           8200
        bid_2_price                                                           46750
        bid_2_volume                                                          22100
        bid_3_price                                                           46700
        bid_3_volume                                                          30200
        ask_1_price                                                           47200
        ask_1_volume                                                           1200
        ask_2_price                                                           47250
        ask_2_volume                                                           1100
        ask_3_price                                                           47300
        ask_3_volume                                                          36200

## Company: Thông tin công ty

> Hiện tại chỉ có nguồn dữ liệu `TCBS` được hỗ trợ

In [17]:
from vnstock3 import Vnstock

company = Vnstock().stock(symbol='VCB', source='TCBS').company

### Tổng quan

In [18]:
company.overview()

,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,HOSE,Ngân hàng,NH,25183,0.233,5589.1,5589.1,2008,23493,2.9,-0.001,0.052,-0.018,Vietcombank,https://vietcombank.com.vn,289,8355

### Hồ sơ

In [19]:
company.profile()

,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies
0,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,Ngân hàng Thương mại Cổ phần Ngoại thương Việ...,Ngày 30/10/1962: Ngân hàng Ngoại thương Việt...,None,Rủi ro địa chính trị và nguy cơ chiến tranh ...,Dịch vụ tài khoản Dịch vụ huy động vốn (tiền...,"Ngân hàng số 1 tại Việt Nam, một trong 100 ng..."

### Cổ đông

In [20]:
company.shareholders()

                  share_holder  share_own_percent
0  Ngân Hàng Nhà Nước Việt Nam             0.7480
1          Mizuho Bank Limited             0.1500
2                         Khác             0.0207

### Giao dịch nội bộ

In [21]:
company.insider_deals()

,deal_announce_date,deal_method,deal_action,deal_quantity,deal_price,deal_ratio
0,2023-12-21,None,Mua,5000.0,80900.0,0.084
1,2020-12-30,None,Bán,-2523.0,64175.0,0.367
2,2020-12-23,None,Bán,-15000.0,63913.0,0.372
3,2020-04-27,None,Mua,10000.0,43434.0,1.019
4,2019-11-29,None,Bán,-10000.0,54974.0,0.595
5,2019-07-26,None,Bán,-21000.0,50592.0,0.733
6,2019-07-22,None,Bán,-37000.0,50914.0,0.723
7,2019-01-16,None,Mua,10000.0,35704.0,1.456
8,2019-01-10,None,Mua,10000.0,35447.0,1.474
9,2018-12-03,None,Mua,10000.0,37380.0,1.346
10,2018-02-08,None,Mua,8000.0,40023.0,1.191
11,2018-01-29,None,Bán,-2829.0,43268.0,1.027
12,2018-01-05,None,Mua,10000.0,34360.0,1.552
13,2018-01-03,None,Bán,-5000.0,34933.0,1.511
14,2018-01-03,None,Bán,-1700.0,34933.0,1.511
15,2017-02-07,None,Mua,10000.0,24445.0,2.588
16,2016-01-12,None,Mua,10000.0,19310.0,3.542
17,2015-03-18,None,Bán,-4000.0,15845.0,4.535
18,2015-02-12,None,Mua,1000.0,16066.0,4.459
19,2014-02-12,None,Mua,10000.0,NaN,NaN

### Công ty con, liên kết

In [22]:
company.subsidiaries()

                                     sub_company_name  sub_own_percent
0   Công ty TNHH Chứng khoán Ngân hàng Thương mại ...            1.000
1   Công Ty TNHH Một Thành Viên Kiều Hối Ngân Hàng...            1.000
2   Công ty TNHH MTV Cho Thuê Tài Chính Ngân Hàng ...            1.000
3       Công ty TNHH Tài Chính Việt Nam Tại Hồng Kông            1.000
4    Ngân Hàng TNHH MTV Ngoại Thương Việt Nam Tại Lào            1.000
5                       Công ty Chuyển Tiền Vcb Money            0.875
6                 Công ty TNHH Cao Ốc Vietcombank 198            0.700
7   Công Ty Liên Doanh Trách Nhiệm Hữu Hạn Vietcom...            0.520
8   Công ty TNHH Quản lý quỹ đầu tư chứng khoán Vi...            0.510
9                  Công ty TNHH Bảo hiểm FWD Việt Nam            0.450
10      Công ty Liên Doanh Hữu Hạn Vietcombank-bonday            0.160
11           Tổng Công ty Cổ phần Bảo hiểm Petrolimex            0.080
12  Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Vi...            0.045
13              Ngân hàng Thương mại Cổ phần Quân đội            0.044
14            Tổng Công ty Hàng không Việt Nam - CTCP            0.010
15  Tổng Công ty Cổ phần Khoan và Dịch vụ khoan Dầ...            0.002
16           Ngân hàng Thương mại Cổ phần Phương Đông            0.000

### Ban lãnh đạo

In [23]:
company.officers()

            officer_name              officer_position  officer_own_percent
3      Nguyễn Danh Lương  Thành viên Hội đồng Quản trị                  0.0
8         Lê Thị Kim Nga  Thành viên Hội đồng Quản trị                  0.0
12            Lê Thị Hoa  Thành viên Hội đồng Quản trị                  0.0
18   Nguyễn Thị Kim Oanh  Thành viên Hội đồng Quản trị                  0.0
10      Đỗ Thị Mai Hương      Thành viên Ban kiểm soát                  0.0
5      Nguyễn Danh Lương   Phụ trách Công bố thông tin                  0.0
4      Nguyễn Danh Lương             Phó Tổng Giám đốc                  0.0
11         Lê Hoàng Tùng             Phó Tổng Giám đốc                  0.0
14         Đào Minh Tuấn             Phó Tổng Giám đốc                  0.0
6      Nguyễn Thanh Tùng    Chủ tịch Hội đồng Quản trị                  0.0
0          Đàm Lam Thanh                          None                  0.0
1       Đậu Thị Thúy Vân                          None                  0.0
2      Nghiêm Xuân Thành                          None                  0.0
7          Nguyễn Mỹ Hào                          None                  0.0
9                Đào Hảo                          None                  0.0
13       Nghiêm Thị Thúy                          None                  0.0
15       Nguyễn Hòa Bình                          None                  0.0
16     Nguyễn Hồng Thắng                          None                  0.0
17        Trương Lệ Hiền                          None                  0.0
19  Phùng Nguyễn Hải Yến                          None                  0.0

### Sự kiện

In [24]:
company.events()

e:\User\miniconda3\envs\AI_prj_final\lib\site-packages\vnstock3\explorer\tcbs\company.py:271: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['event_desc'] = df['event_desc'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

,rsi,rs,id,price,price_change,price_change_ratio,price_change_ratio_1m,event_name,event_code,notify_date,exer_date,reg_final_date,exer_right_date,event_desc
0,52.5,42.0,2569704,88000.0,0.0,0.000,-0.009,VCB - Tổ chức ĐHĐCĐ bất thường 2024,EGME,2024-07-05 00:00:00,2024-08-19 00:00:00,2024-07-19 00:00:00,2024-07-18 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
1,41.4,50.0,2570706,NaN,NaN,NaN,NaN,VCB - BCTC quý 1/2024,KQQY,2024-04-27 00:00:00,2024-04-27 00:00:00,1753-01-01 00:00:00,1753-01-01 00:00:00,VCB - BCTC quý 1/2024
2,56.4,54.0,2566332,94400.0,300.0,0.003,0.050,VCB - Tổ chức ĐHĐCĐ thường niên 2024,AGME,2024-03-12 00:00:00,2024-04-27 00:00:00,2024-03-27 00:00:00,2024-03-26 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
3,52.0,61.0,2564026,89100.0,0.0,0.000,-0.027,"VCB - Niêm yết bổ sung 856,574,691 cổ phiếu",AIS,2023-08-31 00:00:00,2023-08-30 00:00:00,1753-01-01 00:00:00,1753-01-01 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
4,45.5,70.0,2563891,86300.0,-2100.0,-0.024,-0.026,VCB - Tổ chức ĐHĐCĐ bất thường 2023,EGME,2023-08-23 00:00:00,2023-10-06 00:00:00,2023-09-05 00:00:00,2023-08-31 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
5,61.2,56.0,2563509,88819.0,762.0,0.009,0.023,"VCB - Phát hành cổ phiếu trả cổ tức tỷ lệ 18,1%",ISS,2023-07-13 00:00:00,2023-07-25 00:00:00,2023-07-26 00:00:00,2023-07-25 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
6,57.3,82.0,2561470,78743.0,-423.0,-0.005,0.044,VCB - Tổ chức ĐHĐCĐ thường niên 2023,AGME,2023-03-01 00:00:00,2023-04-21 00:00:00,2023-03-21 00:00:00,2023-03-20 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
7,55.6,64.0,2560593,66889.0,-170.0,-0.003,0.053,VCB - Tổ chức ĐHĐCĐ bất thường 2023,EGME,2022-12-20 00:00:00,2023-01-30 00:00:00,2022-12-30 00:00:00,2022-12-29 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
8,45.6,46.0,2476530,68667.0,-2625.0,-0.037,-0.068,VCB - Tổ chức ĐHĐCĐ thường niên 2022,AGME,2022-03-15 00:00:00,2022-04-29 00:00:00,2022-03-28 00:00:00,2022-03-25 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
9,65.5,56.0,2446356,75356.0,-1694.0,-0.022,0.112,VCB - Niêm yết bổ sung 1.023.639.123 cổ phiếu,AIS,2022-01-28 17:47:09,2022-02-14 00:00:00,1753-01-01 00:00:00,1753-01-01 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Vi...
10,44.5,32.0,2395944,64962.0,-524.0,-0.008,0.020,VCB - Phát hành cổ phiếu trả cổ tức tỷ lệ 27.6%,ISS,2021-12-16 11:58:44,2021-12-22 00:00:00,2021-12-23 00:00:00,2021-12-22 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việ...
11,44.5,32.0,2395943,64962.0,-524.0,-0.008,0.020,"VCB - Trả cổ tức Cả năm, 2020 bằng tiền 1200 V...",DIV,2021-12-16 09:00:00,2022-01-05 00:00:00,2021-12-23 00:00:00,2021-12-22 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việ...
12,51.9,30.0,1611831,64306.0,-1246.0,-0.019,-0.043,VCB - Tổ chức ĐHĐCĐ thường niên 2021,AGME,2021-02-24 00:00:00,2021-04-23 00:00:00,2021-03-19 00:00:00,2021-03-18 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
13,NaN,65.0,1481291,63590.0,-1366.0,-0.021,0.140,"VCB - Trả cổ tức Cả năm, 2019 bằng tiền 800 VN...",DIV,2020-12-15 09:00:00,2021-01-08 00:00:00,2020-12-22 00:00:00,2020-12-21 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việ...
14,NaN,44.0,1316877,43434.0,-390.0,-0.009,-0.018,VCB - Tổ chức ĐHĐCĐ thường niên 2020,AGME,2020-05-05 00:00:00,2020-06-26 00:00:00,2020-05-20 00:00:00,2020-05-19 00:00:00,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...

### Tin tức

In [25]:
company.news()

,rsi,rs,price,price_change,price_change_ratio,price_change_ratio_1m,id,title,source,publish_date
0,49.3,46.0,NaN,NaN,NaN,NaN,11286488,Vì sao tiền gửi của khách hàng tại Vietcombank...,TCBS,2024-08-10 07:44:00
1,71.7,64.0,88700.0,-2000.0,-0.022,0.006,11278924,Lãnh đạo cấp cao Vietcombank sang làm Phó Chán...,TCBS,2024-08-02 10:59:00
2,63.7,54.0,90700.0,1500.0,0.017,0.053,11278021,VCB: Thông báo thay đổi nhân sự,TCBS,2024-08-01 17:37:00
3,48.5,42.0,89200.0,1700.0,0.019,0.036,11276160,VCB: Công văn công bố BCTC quý 2/2024 và link,TCBS,2024-07-31 16:37:00
4,48.5,42.0,89200.0,1700.0,0.019,0.036,11276032,VCB: Báo cáo tình hình quản trị công ty 6 thá...,TCBS,2024-07-31 15:58:00
5,46.0,36.0,87500.0,200.0,0.002,0.016,11274489,Vietcombank: Lợi nhuận nửa đầu năm đạt kỷ lục ...,TCBS,2024-07-30 22:21:00
6,46.0,36.0,87500.0,200.0,0.002,0.016,11273764,VCB: Tài liệu họp ĐHĐCĐ bất thường năm 2024,TCBS,2024-07-30 15:16:00
7,46.0,37.0,87300.0,0.0,0.000,0.014,11271831,VCB: Thông báo thay đổi nhân sự công ty,TCBS,2024-07-29 14:14:00
8,46.0,37.0,NaN,NaN,NaN,NaN,11270918,Vietcombank (VCB) có tân Chủ tịch HĐQT,TCBS,2024-07-28 16:30:00
9,46.9,24.0,88100.0,900.0,0.010,0.001,11250229,"VCB chuẩn bị phát hành 6,5% cổ phiếu riêng lẻ ...",TCBS,2024-07-09 13:20:00
10,52.5,42.0,88000.0,0.0,0.000,-0.009,11247744,"ACBS: Vietcombank chuẩn bị bán 6,5% vốn cho Mi...",TCBS,2024-07-05 19:06:00
11,52.5,42.0,88000.0,0.0,0.000,-0.009,11246830,VCB: Thông báo về ngày ĐKCC tổ chức ĐHĐCĐ bất...,TCBS,2024-07-05 09:37:00
12,28.4,30.0,86100.0,900.0,0.011,-0.024,11233290,VCB: CBTT Nghị quyết HĐQT về việc chuẩn bị tổ...,TCBS,2024-07-01 16:19:00
13,28.4,30.0,86100.0,900.0,0.011,-0.024,11232625,Vietcombank chuẩn bị họp cổ đông bất thường bà...,TCBS,2024-07-01 09:48:00
14,29.7,27.0,85200.0,-300.0,-0.004,-0.055,11228898,VCB: HĐQT thông qua giao dịch giữa VCB và VCBS,TCBS,2024-06-26 16:51:00

In [46]:
company.news().to_excel('file.xlsx', index=None)

### Cổ tức

In [26]:
company.dividends()

   exercise_date  cash_year  cash_dividend_percentage issue_method
0       25/07/23       2023                     0.181        share
1       22/12/21       2022                     0.276        share
2       22/12/21       2020                     0.120         cash
3       21/12/20       2019                     0.080         cash
4       30/12/19       2018                     0.080         cash
5       05/10/18       2017                     0.080         cash
6       28/09/17       2016                     0.080         cash
7       09/09/16       2015                     0.100         cash
8       26/06/15       2014                     0.100         cash
9       18/06/14       2013                     0.120         cash
10      26/02/13       2012                     0.120         cash
11      24/02/12       2011                     0.120         cash
12      18/07/11       2011                     0.120        share
13      10/03/10       2009                     0.120         cash
14      01/12/08       2008                     0.120         cash

## Finance: Báo cáo tài chính

In [27]:
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='VCI', source='VCI')

2024-08-12 16:55:46,608 - vnstock3.common.data.data_explorer - WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS

### Bảng cân đối kế toán

In [38]:
stock.finance.balance_sheet(period='1m', lang='vi')

,CP,Năm,Kỳ,Hàng tồn kho ròng,Tài sản lưu động khác,Giá trị ròng tài sản đầu tư,Tài sản dài hạn khác,Các quỹ khác,Các quỹ khác,Vốn Ngân sách nhà nước và quỹ khác,...,NỢ PHẢI TRẢ (Tỷ đồng),TỔNG CỘNG TÀI SẢN (Tỷ đồng),Lợi thế thương mại (Tỷ đồng),Trả trước dài hạn (Tỷ đồng),Tài sản dài hạn khác (Tỷ đồng),Đầu tư dài hạn (Tỷ đồng),Tài sản cố định (Tỷ đồng),Phải thu dài hạn khác (Tỷ đồng),Phải thu về cho vay dài hạn (Tỷ đồng),Phải thu dài hạn (Tỷ đồng)
0,VCI,2024,2,0,400500649851,0,53224683273,0,0,0,...,14246851580952,23105371788635,0.0,8879984392,0,0,32024143832,0,0.0,0
1,VCI,2024,1,0,261218668090,0,54019497651,0,0,0,...,11367295476918,19544604126402,0.0,9017164629,0,0,21879259104,0,0.0,0
2,VCI,2023,4,0,194894059515,0,51610830106,0,0,0,...,9883905148184,17255134656525,0.0,7943878800,0,0,23425609453,0,0.0,0
3,VCI,2023,3,0,226429639030,0,51340225116,0,0,0,...,9625671689274,16917131786375,0.0,8522827154,0,0,21322591745,0,0.0,0
4,VCI,2023,2,0,52662044484,0,51038325192,0,0,0,...,7149696682829,14519562225164,0.0,9086601750,0,0,18824692495,0,0.0,0
5,VCI,2023,1,0,150707604182,0,52893628464,0,0,0,...,8130567126508,14998472092947,0.0,10948712591,0,0,20806365815,0,0.0,0
6,VCI,2022,4,0,51841008271,0,54201919410,0,0,0,...,7747283145208,14242751316822,0.0,13290531600,0,0,23496558588,0,0.0,0
7,VCI,2022,3,0,158416613177,0,55412224927,0,0,0,...,9110375834657,15701703951821,0.0,14510743263,0,0,26726060260,0,0.0,0
8,VCI,2022,2,0,157142540024,0,56093598107,0,0,0,...,9285916800797,16427416373034,0.0,15165653181,0,0,16366064475,0,0.0,0
9,VCI,2022,1,0,155330399563,0,46370044146,0,0,0,...,9895722054419,17045909519104,0.0,6384619412,0,0,12035983058,0,0.0,0
10,VCI,2021,4,0,153897953409,0,48333579135,0,0,0,...,10094401701730,16636264947117,0.0,10702485700,0,0,13155825424,0,0.0,0
11,VCI,2021,3,0,133822392289,0,47279838275,0,0,0,...,7328693345550,13666310426328,0.0,9655486407,0,0,13249224942,0,0.0,0
12,VCI,2021,2,0,70617839039,0,47878610015,0,0,0,...,6213778485845,11516672081700,0.0,10103206889,0,0,15124513070,0,0.0,0
13,VCI,2021,1,0,118086677471,0,49902317498,0,0,0,...,4499383595789,9410284891684,0.0,11225189844,0,0,15491258314,0,0.0,0
14,VCI,2020,4,0,97527648804,0,50200524983,0,0,0,...,3860918605726,8382405125440,0.0,12950546970,0,0,14384201512,0,0.0,0
15,VCI,2020,3,0,8934427514,0,53570956022,0,0,0,...,2747860636658,6747968697132,0.0,16325995278,0,0,16047061220,0,0.0,0
16,VCI,2020,2,0,206889778010,0,80321544030,0,0,0,...,2992277833572,6723779778299,0.0,15147697797,0,0,14163579940,0,0.0,0
17,VCI,2020,1,0,168360406809,0,137653366236,0,0,0,...,3547479001693,7160412080856,0.0,16896096820,0,0,11449628915,0,0.0,0
18,VCI,2019,4,0,15433739031,0,203010616665,0,0,0,...,3191354377816,7242960228473,0.0,17085900679,0,0,9907318916,0,0.0,0
19,VCI,2019,3,0,17040521529,0,55210300562,0,0,0,...,2772228838211,6565027514128,0.0,19288178869,0,0,12481628573,0,0.0,0
20,VCI,2019,2,0,45610630388,0,55985663877,0,0,0,...,2689162580890,6187154600619,0.0,20071136208,0,0,15052880737,0,0.0,0
21,VCI,2019,1,0,19376034517,0,58497309165,0,0,0,...,1887741464445,5503683036361,0.0,22596467372,0,0,16225597128,0,0.0,0
22,VCI,2018,4,0,2684615898,0,59763924859,0,0,0,...,2867018192422,6509995923207,0.0,25494063880,0,0,18226354386,0,0.0,0
23,VCI,2018,3,0,4415594208,0,60557130851,0,0,0,...,3595085540830,7370344558669,0.0,26265838191,0,0,19047282208,0,0.0,0
24,VCI,2018,2,0,4105273019,0,65571030536,0,0,0,...,4323223450011,7919209660201,0.0,31299846411,0,0,20489209280,0,0.0,0
25,VCI,2018,1,0,88999731050,0,40153277637,0,0,0,...,3584778352917,7176055864295,0.0,6049626959,0,0,22594576584,0,0.0,0
26,VCI,2017,4,0,118590746956,0,33742673168,0,0,0,...,3382616547959,6402011745204,0.0,2171535344,0,0,25326131092,0,0.0,0
27,VCI,2017,3,0,237955403298,0,33507019369,0,0,0,...,2705954364807,5360698474640,0.0,2534286044,0,75960000000,28634327913,0,0.0,0
28,VCI,2017,2,0,183934011040,0,23858067233,0,0,0,...,2556041167120,3968999978365,0.0,2911701446,0,75960000000,15921126531,0,0.0,0
29,VCI,2017,1,0,7877662985,0,26743330771,0,0,0,...,1597302770454,2995579067428,0.0,5592666135,0,0,7580072607,0,0.0,433398700
30,VCI,2016,4,0,8287258887,0,23507511542,17100517802,0,0,...,1833990056847,3110547766840,0.0,4433448206,0,0,9489824544,0,0.0,0
31,VCI,2016,3,0,98150524670,0,23565900638,193950060,0,0,...,1846322344545,3013098801142,0.0,5772093553,0,0,11561514905,0,0.0,0
32,VCI,2016,2,0,99230086928,0,24877943972,0,0,0,...,1915349865087,2963133836693,0.0,7112155167,0,0,11805899303,0,0.0,0
33,VCI,2016,1,0,2785363865,0,25806484412,34112989558,0,0,...,1932904919516,2995487250513,0.0,8156185047,0,16670000000,12620824853,0,0.0,0
34,VCI,2015,4,39837900,4592111980,0,24968229303,34112989558,0,0,...,2103940445788,3076737549380,0.0,9817929938,42099600000,42099600000,14899441202,0,0.0,0
35,VCI,2015,3,41526582,28801448457,0,26449483470,21941382767,0,0,...,2382515579675,3303550801940,0.0,11299184105,42099600000,42099600000,14388618817,0,0.0,0
36,VCI,2015,2,74824400,4704944896,0,26417382359,21941382767,0,0,...,1900418596495,2799237475304,0.0,11270092994,17190000000,16924101873,17541598063,0,0.0,0
37,VCI,2015,1,24603400,5166881345,0,30964017968,21941382767,0,0,...,2053641577245,2893776601872,NaN,12780310342,0,18152096502,17351658173,0,NaN,0
38,VCI,2014,4,14179400,6871804516,0,29443792673,21855642000,0,0,...,1959102886391,2688645014807,0.0,14552010828,0,79560000000,17397006733,0,0.0,0
39,VCI,2014,3,20269400,1991797670,0,31219350825,14656994434,0,0,...,2105844338678,2792902743399,0.0,15777920271,0,0,15798290024,0,0.0,0
40,VCI,2014,2,23777720,16469511065,0,29782325178,14656994434,0,0,...,1246073097786,1802154580445,0.0,14420146224,0,0,18246388103,0,0.0,0
41,VCI,2014,1,36637600,4682867183,0,32557819931,14656994434,0,0,...,1939421263881,2496016082259,0.0,15739614019,0,0,10269886048,0,0.0,0
42,VCI,2013,4,16677400,1066062671,0,13063896151,14135173814,0,0,...,1563803125293,2097515889992,NaN,3723030450,500000000000,500000000000,11027268785,0,NaN,0
43,VCI,2013,3,16799000,30228184561,0,13555266349,11048498479,0,0,...,1459543299753,1981776278903,NaN,4125060648,500000000000,500000000000,11906596870,0,NaN,0
44,VCI,2013,2,23124000,2134478587,0,13124451182,11048498479,0,0,...,1664758792832,2151130915921,NaN,3787685481,500000000000,500000000000,13041995330,0,NaN,0
45,VCI,2013,1,14024400,23794284033,0,9459817545,11048498479,0,0,...,1606559817740,2083685987449,NaN,565774769,500000000000,500000000000,15848580825,0,NaN,0

In [36]:
stock.finance.balance_sheet(period='year', lang='vi').columns

Index(['CP', 'Năm', 'Hàng tồn kho ròng', 'Tài sản lưu động khác',
       'Giá trị ròng tài sản đầu tư', 'Tài sản dài hạn khác', 'Các quỹ khác',
       'Các quỹ khác', 'Vốn Ngân sách nhà nước và quỹ khác',
       'Vốn Ngân sách nhà nước và quỹ khác', 'LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ',
       'Lợi thế thương mại', 'Tiền gửi tại ngân hàng nhà nước Việt Nam',
       'Tiền gửi tại các TCTD khác và cho vay các TCTD khác',
       'Dự phòng giảm giá chứng khoán kinh doanh',
       'Các công cụ tài chính phái sinh và khoản nợ tài chính khác',
       'Các công cụ tài chính phái sinh và khoản nợ tài chính khác',
       'Cho vay khách hàng', 'Cho vay khách hàng',
       'Dự phòng rủi ro cho vay khách hàng',
       'Chứng khoán đầu tư sẵn sàng để bán',
       'Chứng khoán đầu tư giữ đến ngày đáo hạn',
       'Dự phòng giảm giá chứng khoán đầu tư', 'Đầu tư vào công ty con',
       'Đầu tư vào công ty liên doanh', 'Dự phòng giảm giá đầu tư dài hạn',
       'Tài sản cố định hữu hình', 'Tài sản cố định thuê tài chính',
       'Tài sản cố định vô hình', 'Tài sản Có khác',
       'Các khoản nợ chính phủ và NHNN Việt Nam',
       'Tiền gửi và vay các Tổ chức tín dụng khác', 'Tiền gửi của khách hàng',
       'Vốn tài trợ, uỷ thác đầu tư của CP và các tổ chức TD khác',
       'Phát hành giấy tờ có giá', 'Các khoản nợ khác',
       'Vốn của tổ chức tín dụng', 'Quỹ của tổ chức tín dụng',
       'Chênh lệch tỷ giá hối đoái', 'Chênh lệch đánh giá lại tài sản',
       'TÀI SẢN NGẮN HẠN (Tỷ đồng)', 'Tiền và tương đương tiền (Tỷ đồng)',
       'Giá trị thuần đầu tư ngắn hạn (Tỷ đồng)',
       'Các khoản phải thu ngắn hạn (Tỷ đồng)',
       'Trả trước cho người bán ngắn hạn (Tỷ đồng)',
       'Phải thu về cho vay ngắn hạn (Tỷ đồng)',
       'Hàng tồn kho, ròng (Tỷ đồng)', 'Tài sản lưu động khác (Tỷ đồng)',
       'TÀI SẢN DÀI HẠN (Tỷ đồng)', 'TỔNG CỘNG NGUỒN VỐN (Tỷ đồng)',
       'Lãi chưa phân phối (Tỷ đồng)', 'Quỹ đầu tư và phát triển (Tỷ đồng)',
       'Cổ phiếu phổ thông (Tỷ đồng)', 'Vốn góp của chủ sở hữu (Tỷ đồng)',
       'Vốn và các quỹ (Tỷ đồng)', 'VỐN CHỦ SỞ HỮU (Tỷ đồng)',
       'Trái phiếu chuyển đổi (Tỷ đồng)',
       'Vay và nợ thuê tài chính dài hạn (Tỷ đồng)', 'Nợ dài hạn (Tỷ đồng)',
       'Người mua trả tiền trước ngắn hạn (Tỷ đồng)',
       'Vay và nợ thuê tài chính ngắn hạn (Tỷ đồng)', 'Nợ ngắn hạn (Tỷ đồng)',
       'NỢ PHẢI TRẢ (Tỷ đồng)', 'TỔNG CỘNG TÀI SẢN (Tỷ đồng)',
       'Lợi thế thương mại (Tỷ đồng)', 'Trả trước dài hạn (Tỷ đồng)',
       'Tài sản dài hạn khác (Tỷ đồng)', 'Đầu tư dài hạn (Tỷ đồng)',
       'Tài sản cố định (Tỷ đồng)', 'Phải thu dài hạn khác (Tỷ đồng)',
       'Phải thu về cho vay dài hạn (Tỷ đồng)', 'Phải thu dài hạn (Tỷ đồng)'],
      dtype='object')

In [29]:
stock.finance.balance_sheet(period='quarter', lang='en').head()

,ticker,yearReport,lengthReport,Net Inventories,Other current assets,Investment in properties,Other non-current assets,Other Reserves,Other Reserves,Budget sources and other funds,...,LIABILITIES (Bn. VND),TOTAL ASSETS (Bn. VND),Good will (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),Long-term investments (Bn. VND),Fixed assets (Bn. VND),Other long-term receivables (Bn. VND),Long-term loans receivables (Bn. VND),Long-term trade receivables (Bn. VND)
0,VCI,2024,2,0,400500649851,0,53224683273,0,0,0,...,14246851580952,23105371788635,0.0,8879984392,0,0,32024143832,0,0.0,0
1,VCI,2024,1,0,261218668090,0,54019497651,0,0,0,...,11367295476918,19544604126402,0.0,9017164629,0,0,21879259104,0,0.0,0
2,VCI,2023,4,0,194894059515,0,51610830106,0,0,0,...,9883905148184,17255134656525,0.0,7943878800,0,0,23425609453,0,0.0,0
3,VCI,2023,3,0,226429639030,0,51340225116,0,0,0,...,9625671689274,16917131786375,0.0,8522827154,0,0,21322591745,0,0.0,0
4,VCI,2023,2,0,52662044484,0,51038325192,0,0,0,...,7149696682829,14519562225164,0.0,9086601750,0,0,18824692495,0,0.0,0

### Báo cáo lãi lỗ

In [30]:
stock.finance.income_statement(period='year', lang='vi').head()

,CP,Năm,Chứng khoán kinh doanh,Chứng khoán kinh doanh,Chứng khoán kinh doanh,Chứng khoán đầu tư,Chứng khoán đầu tư,Cổ đông thiểu số,Cổ đông thiểu số,Lãi/Lỗ ròng trước thuế,...,Tổng thu nhập hoạt động,LN từ HĐKD trước CF dự phòng,Chi phí dự phòng rủi ro tín dụng,LN trước thuế,Thuế TNDN,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông của Công ty mẹ,Lãi cơ bản trên cổ phiếu
0,VCI,2023,0.0,0.0,0.0,0.0,0.0,0,0,570138640134,...,0.0,0.0,0.0,570138640134,-7.823398e+10,-64320454739,-13913526001,491904659394,491904659394,0
1,VCI,2022,0.0,0.0,0.0,0.0,0.0,0,0,1059738713385,...,0.0,0.0,0.0,1059738713385,-1.907605e+11,-250981079495,60220551912,868978185802,868978185802,1999
2,VCI,2021,0.0,0.0,0.0,0.0,0.0,0,0,1850585393088,...,0.0,0.0,0.0,1850585393088,-3.518670e+11,-309748513618,-42118504142,1498718375328,1498718375328,4502
3,VCI,2020,0.0,0.0,0.0,0.0,0.0,0,0,951038957081,...,0.0,0.0,0.0,951038957081,-1.821267e+11,-182422798514,296130854,768912289421,768912289421,4668
4,VCI,2019,0.0,0.0,0.0,0.0,0.0,0,0,855007109256,...,0.0,0.0,0.0,855007109256,-1.618265e+11,-155223164412,-6603367576,693180577268,693180577268,4240

In [37]:
stock.finance.income_statement(period='year', lang='vi').head().columns

Index(['CP', 'Năm', 'Chứng khoán kinh doanh', 'Chứng khoán kinh doanh',
       'Chứng khoán kinh doanh', 'Chứng khoán đầu tư', 'Chứng khoán đầu tư',
       'Cổ đông thiểu số', 'Cổ đông thiểu số', 'Lãi/Lỗ ròng trước thuế',
       'Cố tức đã nhận', 'Cố tức đã nhận', 'Tăng trưởng doanh thu (%)',
       'Doanh thu (Tỷ đồng)',
       'Lợi nhuận sau thuế của Cổ đông công ty mẹ (Tỷ đồng)',
       'Tăng trưởng lợi nhuận (%)', 'Thu nhập tài chính', 'Thu nhập tài chính',
       'Chi phí tiền lãi vay', 'Chi phí tiền lãi vay', 'Doanh thu thuần',
       'Doanh thu thuần', 'Lãi gộp', 'Lãi gộp', 'Chi phí tài chính',
       'Chi phí tài chính', 'Chi phí quản lý DN', 'Chi phí quản lý DN',
       'Lãi/Lỗ từ hoạt động kinh doanh', 'Lãi/Lỗ từ hoạt động kinh doanh',
       'Lãi lỗ trong công ty liên doanh, liên kết', 'Thu nhập/Chi phí khác',
       'Giá vốn hàng bán', 'Chi phí bán hàng', 'Chi phí bán hàng',
       'Doanh thu bán hàng và cung cấp dịch vụ',
       'Các khoản giảm trừ doanh thu', 'Lãi/lỗ từ công ty liên doanh',
       'Thu nhập khác', 'Lợi nhuận khác', 'Thu nhập lãi và các khoản tương tự',
       'Chi phí lãi và các khoản tương tự', 'Thu nhập lãi thuần',
       'Thu nhập từ hoạt động dịch vụ', 'Chi phí hoạt động dịch vụ',
       'Lãi thuần từ hoạt động dịch vụ', 'Kinh doanh ngoại hối và vàng',
       'Hoạt động khác', 'Chi phí hoạt động khác',
       'Lãi/lỗ thuần từ hoạt động khác', 'Tổng thu nhập hoạt động',
       'LN từ HĐKD trước CF dự phòng', 'Chi phí dự phòng rủi ro tín dụng',
       'LN trước thuế', 'Thuế TNDN', 'Chi phí thuế TNDN hiện hành',
       'Chi phí thuế TNDN hoãn lại', 'Lợi nhuận thuần',
       'Cổ đông của Công ty mẹ', 'Lãi cơ bản trên cổ phiếu'],
      dtype='object')

In [31]:
stock.finance.income_statement(period='quarter', lang='en').head()

,ticker,yearReport,lengthReport,Minority Interest,Minority Interest,Net Profit/Loss before tax,Dividends received,Dividends received,Provision for credit losses,Provision for credit losses,...,Net Other income/expenses,Total operating revenue,Operating Profit before Provision,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis
0,VCI,2024,2,0,0,3.437661e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,343766121537,-6.455944e+10,-64821621464,262179824,279206679897,279206679897,0
1,VCI,2024,1,0,0,2.275405e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,227540468148,-2.978401e+10,-37710331505,7926325750,197756462393,197756462393,0
2,VCI,2023,4,0,0,1.491318e+11,0.0,0.0,0.0,1.129200e+10,...,0.0,0.0,0.0,149131831394,-2.618133e+10,-7570702516,-18610626203,122950502675,122950502675,0
3,VCI,2023,3,0,0,2.095692e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,209569229621,-3.056605e+10,-33158501552,2592446586,179003174655,179003174655,0
4,VCI,2023,2,0,0,1.306470e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,130647004339,-1.375038e+10,-9894721068,-3855663920,116896619351,116896619351,0

### Báo cáo lưu chuyển tiền tệ

In [32]:
stock.finance.cash_flow(period='year').head()

,ticker,yearReport,Cash and cash equivalents,Unrealized foreign exchange gain/loss,Profit/Loss from disposal of fixed assets,Profit/Loss from disposal of fixed assets,Profit/Loss from investing activities,Interest Expense,Interest income and dividends,Increase/Decrease in receivables,...,Operating profit before changes in working capital,Net Cash Flows from Operating Activities before BIT,Payment from reserves,Purchase of fixed assets,Gain on Dividend,Net Cash Flows from Investing Activities,Increase in charter captial,Cash flows from financial activities,"Collection of loans, proceeds from sales of debts instruments (Bn. VND)","Loans granted, purchases of debt instruments (Bn. VND)"
0,VCI,2023,3423501614803,0,0.0,0.0,0,562553033255,-1.032191e+11,-7.134590e+11,...,-5407321967895,0.0,0.0,-7898483136,0,-7898483136,24001188000,1727849074143,0,0
1,VCI,2022,1131748599533,0,0.0,0.0,154602984,477360036322,-5.948490e+10,1.564054e+11,...,2006811362129,0.0,0.0,-22377694322,0,-21692694322,25000000000,-1428442857143,0,0
2,VCI,2021,642512983590,0,0.0,0.0,0,330776772616,-4.785212e+10,1.255581e+10,...,-5732733292320,0.0,0.0,-6428566364,0,-6428566364,13500000000,4245676777200,0,0
3,VCI,2020,794511762602,0,0.0,0.0,-500000000,173513458172,-2.094800e+10,-2.008506e+11,...,-1673271187005,0.0,0.0,-13821350820,0,-13321350820,13452168000,432858721500,0,0
4,VCI,2019,1144361568890,0,0.0,0.0,-8900000,165277553123,-4.476748e+10,0.000000e+00,...,-1299721219619,0.0,0.0,-8838018881,0,-8829118881,16801320000,113369230,0,0

In [33]:
stock.finance.income_statement(period='quarter', lang='en').head()

,ticker,yearReport,lengthReport,Minority Interest,Minority Interest,Net Profit/Loss before tax,Dividends received,Dividends received,Provision for credit losses,Provision for credit losses,...,Net Other income/expenses,Total operating revenue,Operating Profit before Provision,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis
0,VCI,2024,2,0,0,3.437661e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,343766121537,-6.455944e+10,-64821621464,262179824,279206679897,279206679897,0
1,VCI,2024,1,0,0,2.275405e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,227540468148,-2.978401e+10,-37710331505,7926325750,197756462393,197756462393,0
2,VCI,2023,4,0,0,1.491318e+11,0.0,0.0,0.0,1.129200e+10,...,0.0,0.0,0.0,149131831394,-2.618133e+10,-7570702516,-18610626203,122950502675,122950502675,0
3,VCI,2023,3,0,0,2.095692e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,209569229621,-3.056605e+10,-33158501552,2592446586,179003174655,179003174655,0
4,VCI,2023,2,0,0,1.306470e+11,0.0,0.0,0.0,0.000000e+00,...,0.0,0.0,0.0,130647004339,-1.375038e+10,-9894721068,-3855663920,116896619351,116896619351,0

### Chỉ số tài chính

In [43]:
stock.finance.ratio(period='year', lang='vi').head()

  Meta          Chỉ tiêu định giá                                              \
    CP   Năm Kỳ               P/B Vốn hóa (Tỷ đồng) Số CP lưu hành (Triệu CP)
0  VCI  2023  5          2.688663    19818750000000                 437500000
1  VCI  2022  5          2.866248    18617620767750                 435499901
2  VCI  2021  5          1.183493     7742250000000                 333000000
3  VCI  2020  5          2.666309    12055680000000                 165600000
4  VCI  2019  5          2.418360     9798240000000                 164400000

                                                 ...  \
         P/E       P/S P/Cash Flow    EPS (VND)  ...
0  40.289820  8.015800   -4.550224  1124.353507  ...
1  21.424727  5.898666    4.975461  1995.357941  ...
2   5.165914  2.088510   -2.064593  4500.655782  ...
3  15.678875  6.970247  -21.093469  4643.190154  ...
4  14.135191  6.358594  -28.722550  4216.426869  ...

  Chỉ tiêu hiệu quả hoạt động                             \
               Vòng quay TSCĐ Số ngày thu tiền bình quân
0                  105.385605                        NaN
1                  172.225781                        NaN
2                  269.213152                        NaN
3                  142.402909                        NaN
4                  109.544483                        NaN

                                                                      \
  Số ngày tồn kho bình quân Số ngày thanh toán bình quân Chu kỳ tiền
0                       0.0                    30.140870         NaN
1                       0.0                    78.715859         NaN
2                       0.0                    94.585936         NaN
3                       0.0                    39.269900         NaN
4                       0.0                     4.820025         NaN

                         Chỉ tiêu cơ cấu nguồn vốn                           \
  Vòng quay hàng tồn kho          (Vay NH+DH)/VCSH   Nợ/VCSH TSCĐ / Vốn CSH
0                    0.0                  1.218152  1.340876       0.003178
1                    0.0                  0.973942  1.192721       0.003617
2                    0.0                  0.972610  1.543047       0.002011
3                    0.0                  0.596293  0.853905       0.003181
4                    0.0                  0.358125  0.787676       0.002445


  Vốn CSH/Vốn điều lệ
0            1.668076
1            1.469895
2            1.480394
3            1.023192
4            0.916860

[5 rows x 37 columns]

In [40]:
stock.finance.ratio(period='year', lang='vi').head().columns

MultiIndex([(                       'Meta',                           'CP'),
            (                       'Meta',                          'Năm'),
            (                       'Meta',                           'Kỳ'),
            (          'Chỉ tiêu định giá',                          'P/B'),
            (          'Chỉ tiêu định giá',            'Vốn hóa (Tỷ đồng)'),
            (          'Chỉ tiêu định giá',    'Số CP lưu hành (Triệu CP)'),
            (          'Chỉ tiêu định giá',                          'P/E'),
            (          'Chỉ tiêu định giá',                          'P/S'),
            (          'Chỉ tiêu định giá',                  'P/Cash Flow'),
            (          'Chỉ tiêu định giá',                    'EPS (VND)'),
            (          'Chỉ tiêu định giá',                   'BVPS (VND)'),
            (          'Chỉ tiêu định giá',                    'EV/EBITDA'),
            ( 'Chỉ tiêu khả năng sinh lợi',       'Biên lợi nhuận gộp (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',      'Biên lợi nhuận ròng (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',                      'ROE (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',                     'ROIC (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',                      'ROA (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',                'Biên EBIT (%)'),
            ( 'Chỉ tiêu khả năng sinh lợi',             'EBITDA (Tỷ đồng)'),
            ( 'Chỉ tiêu khả năng sinh lợi',               'EBIT (Tỷ đồng)'),
            ( 'Chỉ tiêu khả năng sinh lợi',           'Tỷ suất cổ tức (%)'),
            (       'Chỉ tiêu thanh khoản',  'Chỉ số thanh toán hiện thời'),
            (       'Chỉ tiêu thanh khoản',   'Chỉ số thanh toán tiền mặt'),
            (       'Chỉ tiêu thanh khoản',      'Chỉ số thanh toán nhanh'),
            (       'Chỉ tiêu thanh khoản',     'Khả năng chi trả lãi vay'),
            (       'Chỉ tiêu thanh khoản',            'Đòn bẩy tài chính'),
            ('Chỉ tiêu hiệu quả hoạt động',            'Vòng quay tài sản'),
            ('Chỉ tiêu hiệu quả hoạt động',               'Vòng quay TSCĐ'),
            ('Chỉ tiêu hiệu quả hoạt động',   'Số ngày thu tiền bình quân'),
            ('Chỉ tiêu hiệu quả hoạt động',    'Số ngày tồn kho bình quân'),
            ('Chỉ tiêu hiệu quả hoạt động', 'Số ngày thanh toán bình quân'),
            ('Chỉ tiêu hiệu quả hoạt động',                  'Chu kỳ tiền'),
            ('Chỉ tiêu hiệu quả hoạt động',       'Vòng quay hàng tồn kho'),
            (  'Chỉ tiêu cơ cấu nguồn vốn',             '(Vay NH+DH)/VCSH'),
            (  'Chỉ tiêu cơ cấu nguồn vốn',                      'Nợ/VCSH'),
            (  'Chỉ tiêu cơ cấu nguồn vốn',               'TSCĐ / Vốn CSH'),
            (  'Chỉ tiêu cơ cấu nguồn vốn',          'Vốn CSH/Vốn điều lệ')],
           )

In [35]:
stock.finance.ratio(period='quarter', lang='en').head()

    Meta                         Chỉ tiêu định giá                           \
  ticker yearReport lengthReport               P/B Market Capital (Bn. VND)
0    VCI       2024            2          2.259753           20018070000000
1    VCI       2024            1          2.571899           21167010000000
2    VCI       2023            4          3.092259           22793750000000
3    VCI       2023            3          2.520071           18375000000000
4    VCI       2023            2          2.519975           18571875000000

                                                                    \
  Outstanding Share (Mil. Shares)        P/E       P/S P/Cash Flow
0                       441900000  25.451700  6.266316   -4.713715
1                       441900000  33.973894  7.615216   -4.399652
2                       437500000  46.238494  9.219055   -5.222052
3                       437500000  46.087220  7.460683 -125.437258
4                       437500000  54.210541  8.012570   12.053285

               ... Chỉ tiêu hiệu quả hoạt động                         \
    EPS (VND)  ...        Fixed Asset Turnover Days Sales Outstanding
0  631.832270  ...                  129.528632                    NaN
1  447.514058  ...                  130.111085                    NaN
2  281.029720  ...                  105.385605                    NaN
3  409.150113  ...                  116.656253                    NaN
4  267.192273  ...                  103.182976                    NaN

                                                                  \
  Days Inventory Outstanding Days Payable Outstanding Cash Cycle
0                        0.0                76.735113        NaN
1                        0.0                41.382358        NaN
2                        0.0                30.140870        NaN
3                        0.0                33.556763        NaN
4                        0.0                47.975578        NaN

                     Chỉ tiêu cơ cấu nguồn vốn              \
  Inventory Turnover (ST+LT borrowings)/Equity Debt/Equity
0                0.0                  1.398891    1.608265
1                0.0                  1.252192    1.390102
2                0.0                  1.218152    1.340876
3                0.0                  1.196291    1.320130
4                0.0                  0.843197    0.970126


  Fixed Asset-To-Equity Owners' Equity/Charter Capital
0              0.003615                       2.004644
1              0.002676                       1.850488
2              0.003178                       1.668076
3              0.002924                       1.650025
4              0.002554                       1.667768

[5 rows x 37 columns]